version: '3'

services:
  app:
    container_name: mytomcat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Fundacion_BA:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_DATABASE: fundacionba2
      MYSQL_USER: root
      MYSQL_PASSWORD: administrador
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

volumes:
  db-data:
