version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=administrador
      - MYSQL_DATABASE=fundacionba2
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
