version: '3'

services:
  app:
    container_name: Contenedor_FBAnimal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/db:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    container_name: db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=administrador
      - MYSQL_DATABASE=fundacionba2
    restart: always
    volumes:
      - ./volumes/db:/data/db

volumes:
  db-data:
